version: '2'

networks:
  lnmpnet:
    driver: bridge

services:

  # nginx service
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}nginx
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
    volumes:
      - ./share:/share
      - ./app/html:/var/www/html 
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./log/nginx/access.log:/var/log/nginx/access.log
      - ./log/nginx/error.log:/var/log/nginx/error.log
    depends_on:
      - php
    networks:
      - lnmpnet

  # php service
  php:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    container_name: ${APP_NAME}php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    volumes:
      - ./share:/share
      - ./app/backend:/var/www/backend
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - redis    
      - mysql  
    networks:
      - lnmpnet

  # mysql service
  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - ./share:/share
      - ./data/mysql-files:/var/lib/mysql-files
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - lnmpnet

  # redis service
  redis:
    image: redis:6-alpine
    container_name: ${APP_NAME}redis
    restart: unless-stopped
    tty: true
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SERVICE_NAME: redis
      SERVICE_TAGS: dev
    volumes:
      - ./share:/share
      - ./data/redis:/data
    networks:
      - lnmpnet        
